// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGt2LWzXcYMWrDhSLn5KmyCqZrK_dSCSc',
    appId: '1:686347798143:web:b3b0555f6907f979b7a14a',
    messagingSenderId: '686347798143',
    projectId: 'tts06e',
    authDomain: 'tts06e.firebaseapp.com',
    storageBucket: 'tts06e.appspot.com',
    measurementId: 'G-0YZWVCGG9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNQuoVj91lVuoqMnE-HEfygnY1lZ2eVo',
    appId: '1:686347798143:android:b006bf1841b4672cb7a14a',
    messagingSenderId: '686347798143',
    projectId: 'tts06e',
    storageBucket: 'tts06e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXGUEbtXyh5vqbc0MTQOxDBV7BzkDA2uQ',
    appId: '1:686347798143:ios:160cea555f03651db7a14a',
    messagingSenderId: '686347798143',
    projectId: 'tts06e',
    storageBucket: 'tts06e.appspot.com',
    iosBundleId: 'com.example.tts06e',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXGUEbtXyh5vqbc0MTQOxDBV7BzkDA2uQ',
    appId: '1:686347798143:ios:cf3f4116969fbf2db7a14a',
    messagingSenderId: '686347798143',
    projectId: 'tts06e',
    storageBucket: 'tts06e.appspot.com',
    iosBundleId: 'com.example.tts06e.RunnerTests',
  );
}
