// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDamJ7m8dY2mdNE3WZcV6KEmxvZolP4cmg',
    appId: '1:530739339374:web:e757ed5ada126f11a1067f',
    messagingSenderId: '530739339374',
    projectId: 'flutterproject-325f0',
    authDomain: 'flutterproject-325f0.firebaseapp.com',
    storageBucket: 'flutterproject-325f0.appspot.com',
    measurementId: 'G-3EG1FMSD96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTR1qNrAku4k_E_biOLnTP4Sg69Zyd_60',
    appId: '1:530739339374:android:e0fec4aabdd12a90a1067f',
    messagingSenderId: '530739339374',
    projectId: 'flutterproject-325f0',
    storageBucket: 'flutterproject-325f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBun7pOKNVEsWCbH6noERvB1WpaRHJlTWc',
    appId: '1:530739339374:ios:708053a37edf84c8a1067f',
    messagingSenderId: '530739339374',
    projectId: 'flutterproject-325f0',
    storageBucket: 'flutterproject-325f0.appspot.com',
    iosBundleId: 'com.example.fizaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBun7pOKNVEsWCbH6noERvB1WpaRHJlTWc',
    appId: '1:530739339374:ios:6702e22aabb584dda1067f',
    messagingSenderId: '530739339374',
    projectId: 'flutterproject-325f0',
    storageBucket: 'flutterproject-325f0.appspot.com',
    iosBundleId: 'com.example.fizaApp.RunnerTests',
  );
}
